name: PharmaChain CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
      redis:
        image: redis:7.0
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./backend
      
      - name: Run tests
        run: npm test
        working-directory: ./backend
      
      - name: Build Docker images
        run: |
          docker build -t pharma-backend ./backend
          docker build -t pharma-frontend ./frontend
          docker build -t pharma-ai ./ai-engine

  deploy-prod:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push Docker images
        run: |
          docker tag pharma-backend ${{ secrets.DOCKERHUB_USERNAME }}/pharma-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pharma-backend:latest
          
          docker tag pharma-frontend ${{ secrets.DOCKERHUB_USERNAME }}/pharma-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pharma-frontend:latest
          
          docker tag pharma-ai ${{ secrets.DOCKERHUB_USERNAME }}/pharma-ai:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pharma-ai:latest
      
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v3
        with:
          namespace: pharmachain
          manifests: |
            ./k8s/deployment.yaml
            ./k8s/service.yaml
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pharma-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/pharma-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/pharma-ai:latest